import { ArrowUpRight, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { Brand } from "./Brand";
import { siteConfig } from "@/data/site";

const columns = [
  { title: "Company", links: [["About Us", "#about"], ["Why NewEra", "#why"], ["Careers", "#careers"], ["Contact", "#contact"]] },
  { title: "Programs", links: [["Full Stack Web Development", "/courses/full-stack-web-development"], ["AI Automation", "/courses/ai-automation"], ["DSAI", "/courses/data-science-ai"]] },
  { title: "Resources", links: [["FAQs", "#faq"], ["Learning Journey", "#journey"], ["Projects", "#projects"]] },
];
function ContactRow({ icon: Icon, value, label }: { icon: typeof Phone; value: string; label: string }) { return <div className="flex items-center gap-3 text-sm text-muted-foreground"><Icon className="h-4 w-4 text-primary"/><span>{value || `${label} coming soon`}</span></div>; }
export function Footer() { return <footer id="contact" className="border-t border-border bg-surface-deep"><div className="page-shell py-16"><div className="grid gap-12 lg:grid-cols-[1.2fr_2fr]"><div><Brand/><p className="mt-5 max-w-xs text-sm leading-6 text-muted-foreground">Build Skills. Build the Future. Practical technology learning for the careers of tomorrow.</p></div><div className="grid grid-cols-2 gap-8 md:grid-cols-4">{columns.map((col) => <div key={col.title}><h3 className="text-sm font-semibold">{col.title}</h3><ul className="mt-5 space-y-3">{col.links.map(([label,href]) => <li key={label}><a className="footer-link" href={href}>{label}</a></li>)}</ul></div>)}<div><h3 className="text-sm font-semibold">Contact</h3><div className="mt-5 space-y-3"><ContactRow icon={Phone} value={siteConfig.contact.phone} label="Phone"/><ContactRow icon={Mail} value={siteConfig.contact.email} label="Email"/><ContactRow icon={MessageCircle} value={siteConfig.contact.whatsapp} label="WhatsApp"/><ContactRow icon={MapPin} value={siteConfig.contact.location} label="Location"/></div></div></div></div><div className="mt-14 flex flex-col gap-5 border-t border-border pt-7 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><p>© 2026 NewEra Solution. All rights reserved.</p><div className="flex flex-wrap gap-5"><a href="#">Privacy Policy</a><a href="#">Terms & Conditions</a>{Object.entries(siteConfig.socials).map(([name,href]) => <a key={name} href={href} className="capitalize">{name}<ArrowUpRight className="ml-1 inline h-3 w-3"/></a>)}</div></div></div></footer>; }
